/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor1;

import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Lenovo
 */
public class Login extends javax.swing.JFrame {
public static String username,password;
    /**
     * Creates new form Login
     */
public String flag = "message";
public int amount;
    public Login() {
        initComponents();
    }
    public Login(String flag,int amount) {
        initComponents();
        this.flag = flag;
        this.amount = amount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Loginlb = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        msgLbl = new javax.swing.JLabel();
        msgLbl1 = new javax.swing.JLabel();
        passwordF = new javax.swing.JPasswordField();
        cancelBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        setMaximumSize(new java.awt.Dimension(466, 420));
        setMinimumSize(new java.awt.Dimension(466, 420));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(466, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(466, 400));
        jPanel1.setLayout(null);

        Loginlb.setBackground(new java.awt.Color(0, 204, 204));
        Loginlb.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Loginlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Loginlb.setText("Admin Login");
        Loginlb.setOpaque(true);
        jPanel1.add(Loginlb);
        Loginlb.setBounds(0, 0, 466, 51);

        usernameTF.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        usernameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTF.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 204, 204))); // NOI18N
        usernameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(usernameTF);
        usernameTF.setBounds(106, 69, 253, 87);
        usernameTF.getAccessibleContext().setAccessibleName("");

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("Login");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(175, 279, 120, 44);

        msgLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        msgLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(msgLbl);
        msgLbl.setBounds(111, 341, 184, 28);

        msgLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        msgLbl1.setForeground(new java.awt.Color(0, 204, 204));
        msgLbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        msgLbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        msgLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msgLbl1MouseClicked(evt);
            }
        });
        jPanel1.add(msgLbl1);
        msgLbl1.setBounds(301, 341, 58, 28);

        passwordF.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        passwordF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordF.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 204, 204))); // NOI18N
        jPanel1.add(passwordF);
        passwordF.setBounds(106, 170, 253, 87);

        cancelBtn.setBackground(new java.awt.Color(0, 153, 153));
        cancelBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minor1/ic_cancel_24px_1.png"))); // NOI18N
        cancelBtn.setText(" CANCEL");
        cancelBtn.setBorder(null);
        cancelBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn);
        cancelBtn.setBounds(120, 390, 110, 40);

        clearBtn.setBackground(new java.awt.Color(0, 153, 153));
        clearBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minor1/trash-simple-2.png"))); // NOI18N
        clearBtn.setText("CLEAR");
        clearBtn.setBorder(null);
        clearBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn);
        clearBtn.setBounds(240, 390, 110, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         username = usernameTF.getText();
        password = passwordF.getText();
       Boolean temp = new LoginC().check();
       if(temp){
                        msgLbl.setText("Login succesfull");
         
             switch (flag) {
                 case "withdraw":
                     {
                         Boolean flag1 = new UserTransaction().withdraw(amount);
                         if(flag1){
                             JOptionPane.showMessageDialog(this, "TRANSACTION SUCCESSFULL!\nPLEASE MAKE SURE TO TAKE MONEY FROM THE ADMIN OR OWNER");
                             this.setVisible(false);
                             new UserHome().setVisible(true);
                         }
                         else{
                             JOptionPane.showMessageDialog(this, "TRANSACTION FAILED!\nNO MONEY DEDUCTED");
                             this.setVisible(false);
                             new UserHome().setVisible(true);
                         }
                         break;
                     }
                 case "deposit":
                     {
                         Boolean flag1 = new UserTransaction().deposit(amount);
                         if(flag1){
                             JOptionPane.showMessageDialog(this, "TRANSACTION SUCCESSFULL!\nPLEASE MAKE SURE TO TAKE MONEY FROM THE ADMIN OR OWNER");
                             this.setVisible(false);
                             new UserHome().setVisible(true);
                         }
                         else{
                             JOptionPane.showMessageDialog(this, "TRANSACTION FAILED!\nNO MONEY DEPOSITED");
                             this.setVisible(false);
                             new UserHome().setVisible(true);
                         }
                         break;
                     }
                 default:
                     this.setVisible(false);
                     new Home().setVisible(true);
                     break;
             }
       }
       else{
           switch (flag) {
               case "withdraw":
               {
                                       JOptionPane.showMessageDialog(this, "WRONG USERNAME OF PASSWORD!\nTRANSACTION FAILED!\nNO MONEY DEDUCTED");
                                       JOptionPane.showMessageDialog(this, "IN CASE, ADMIN/OWNER HAS FORGOT HIS PASSWORD\nHE MUST FIRST CHANGE PASSWORD BY LOGGIN IN!!!");

                                      this.setVisible(false);
                                       new UserHome().setVisible(true);
                                      break;
               }
                  case "deposit":
               {
                                       JOptionPane.showMessageDialog(this, "WRONG USERNAME OF PASSWORD!\nTRANSACTION FAILED!\nNO MONEY DEDUCTED");
                                       JOptionPane.showMessageDialog(this, "IN CASE, ADMIN/OWNER HAS FORGOT HIS PASSWORD\nHE MUST FIRST CHANGE PASSWORD BY LOGGING IN!!!");                                    
                                       this.setVisible(false);
                                       new UserHome().setVisible(true);
                                      break;
               }
                  default:
           JOptionPane.showMessageDialog(this, "Wrong Username or Password!\nTry Again");
           usernameTF.setText("");
            passwordF.setText("");

           
//           msgLbl.setText("Forgot password? Click");
//           msgLbl1.setText("here!");
           
       }
       }
//       if(username.equals("admin") && password.equals("admin")){
//         System.out.println("Login succesfull");
//         this.setVisible(false);
//         new Home().setVisible(true);
//       }
//       else{
//           JOptionPane.showMessageDialog(this, "Wrong Username or Password!");
//           msgLbl.setText("Forgot password? Click");
//           msgLbl1.setText("here!");
//
//       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new nav().setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        usernameTF.setText("");
        passwordF.setText("");
        

        jPanel1.setFocusable(true);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void msgLbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msgLbl1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_msgLbl1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Loginlb;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msgLbl;
    private javax.swing.JLabel msgLbl1;
    private javax.swing.JPasswordField passwordF;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
