/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor1;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class PinChange extends javax.swing.JFrame {

    /**
     * Creates new form PinChange
     */
    public PinChange() {
        initComponents();
    }

    public Boolean onlyDigits(String str, int n) 
    { 
        // Traverse the string from 
        // start to end 
        for (int i = 0; i < n; i++) { 
  
            // Check if character is 
            // digit from 0-9 
            // then return true 
            // else false 
            if (str.charAt(i) >= '0'
                && str.charAt(i) <= '9') { 
                return true; 
            } 
            else { 
                return false; 
            } 
        } 
        return false; 
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Loginlb = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        newpasswordTF1 = new javax.swing.JPasswordField();
        newpasswordTF2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Loginlb.setBackground(new java.awt.Color(0, 204, 204));
        Loginlb.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Loginlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Loginlb.setText("CHANGE PIN");
        Loginlb.setOpaque(true);

        passwordTF.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        passwordTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordTF.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "enter current pin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(0, 204, 204))); // NOI18N
        passwordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTFKeyPressed(evt);
            }
        });

        newpasswordTF1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        newpasswordTF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newpasswordTF1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "enter new pin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(0, 204, 204))); // NOI18N
        newpasswordTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpasswordTF1ActionPerformed(evt);
            }
        });
        newpasswordTF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newpasswordTF1KeyPressed(evt);
            }
        });

        newpasswordTF2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        newpasswordTF2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newpasswordTF2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "re-enter pin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(0, 204, 204))); // NOI18N
        newpasswordTF2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newpasswordTF2KeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Loginlb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newpasswordTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newpasswordTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Loginlb, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newpasswordTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(newpasswordTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newpasswordTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpasswordTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpasswordTF1ActionPerformed

    private void passwordTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTFKeyPressed
        // TODO add your handling code here:
//       char ch = evt.getKeyChar();
//        if(!(Character.isDigit(ch))){
//            evt.consume();
//        }
        
    }//GEN-LAST:event_passwordTFKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String password = passwordTF.getText();

        if(password.equals(AtmPin.pin)){
                            String newpassword1 = newpasswordTF1.getText();
                            String newpassword2 = newpasswordTF2.getText();
                            
                            if(newpassword1.equals("") || newpassword2.equals(""))
                            JOptionPane.showMessageDialog(this, "MUST ENTER NEW PIN!!!\nALL FIELDS ARE COMPULSORY TO FILL\n");      
                           
                            
                            else if (onlyDigits(newpassword1,newpassword1.length()) && onlyDigits(newpassword2,newpassword2.length()) )
                            {
                             if(newpassword1.equals(newpassword2)){
                                Boolean flag = new UserTransaction().changePin(newpassword1);
                                if(flag){
                                             JOptionPane.showMessageDialog(this, "PIN CHANGED SUCCESSFULLY\nMUST LOGIN AGAIN TO MAKE FURTHER TRANSACTIONS!!!");      
                                            this.setVisible(false);
                                            new AtmPin().setVisible(true);
                                } 
                                else{
                                                            JOptionPane.showMessageDialog(this, "CHANGE PASSWORD - ACTION FAILED!!!\n");      
                                                passwordTF.setText("");
                                               newpasswordTF1.setText("");
                                               newpasswordTF2.setText("");
                                }
                            }
                            else{
                                             JOptionPane.showMessageDialog(this, "NEW PASSWORD DO NOT MATCH \nPLEASE RE-ENTER CORRECTLY!!!");      
                                                passwordTF.setText("");
                                               newpasswordTF1.setText("");
                                               newpasswordTF2.setText("");
                            }
          
            }
                            else{
                                                     JOptionPane.showMessageDialog(this, "ONLY NUMERIC VALUES ACCEPTED\nPLEASE ENTER CORRECT PASSWORD!!!");      
                                                          passwordTF.setText("");
                                                           newpasswordTF1.setText("");
                                                          newpasswordTF2.setText("");
                            }
        }
        else{
                 JOptionPane.showMessageDialog(this, "WRONG CURRENT PASSWORD\nPLEASE ENTER CORRECT PASSWORD!!!");      
                 passwordTF.setText("");
                 newpasswordTF1.setText("");
                 newpasswordTF2.setText("");
//                 passwordTF.setCursor(Cursor (c));

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void newpasswordTF1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newpasswordTF1KeyPressed
//char ch = evt.getKeyChar();
//        if(!(Character.isDigit(ch))){
//            evt.consume();
//        }        // TODO add your handling code here:
    }//GEN-LAST:event_newpasswordTF1KeyPressed

    private void newpasswordTF2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newpasswordTF2KeyPressed
//char ch = evt.getKeyChar();
//        if(!(Character.isDigit(ch))){
//            evt.consume();
//        }        // TODO add your handling code here:
    }//GEN-LAST:event_newpasswordTF2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PinChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Loginlb;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newpasswordTF1;
    private javax.swing.JPasswordField newpasswordTF2;
    private javax.swing.JPasswordField passwordTF;
    // End of variables declaration//GEN-END:variables
}
