/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor1;


import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Lenovo
 */
public class HistoryAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HistoryAdmin
     */
    public HistoryAdmin() {
        initComponents();
        setTbl();
    }

    
    void setTbl(){
    Boolean flag = new AdminTransaction().setTbl();
    if(flag == false)
            JOptionPane.showMessageDialog(this, "SORRY!!!\nSome Error Occured");
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Loginlb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyAdminTbl = new javax.swing.JTable();
        printBtn = new javax.swing.JButton();
        goBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Loginlb.setBackground(new java.awt.Color(0, 204, 204));
        Loginlb.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Loginlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Loginlb.setText("HISTORY");
        Loginlb.setOpaque(true);

        historyAdminTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUSTOMER NAME", "CARDNUMBER", "ACCOUNT TYPE", "TRANSACTION TYPE", "DATE", "TIME", "AMOUNT"
            }
        ));
        jScrollPane1.setViewportView(historyAdminTbl);

        printBtn.setBackground(new java.awt.Color(0, 204, 204));
        printBtn.setText("Print");
        printBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        goBackBtn.setBackground(new java.awt.Color(0, 204, 204));
        goBackBtn.setText("Go Back");
        goBackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Loginlb, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(goBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Loginlb, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        try {
            Boolean temp = historyAdminTbl.print();
            if(temp==false)
                JOptionPane.showMessageDialog(this, "PRINTER NOT FOUND");
        } catch (PrinterException ex) {
                            JOptionPane.showMessageDialog(this, "PRINTER NOT FOUND");

            Logger.getLogger(HistoryAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_printBtnActionPerformed

    private void goBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_goBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Loginlb;
    private javax.swing.JButton goBackBtn;
    public static javax.swing.JTable historyAdminTbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printBtn;
    // End of variables declaration//GEN-END:variables

// TODO add your handling code here:
//         JTextArea tf = new JTextArea();
//        tf.append("History");
//                   tf.append("\n\nCustomer Name");
//           tf.append("\tCardnumber");
//             tf.append("\tAccount type");
//           tf.append("\tTransaction type");
//            tf.append("      Date");
//            tf.append("\t      Time");
//            tf.append("\tAmount");
//            
//
//            for(int i =0 ; i < historyAdminTbl.getRowCount();i++){
//            
//            String Customer = historyAdminTbl.getValueAt(i, 0).toString();
//            String Cardnumber= historyAdminTbl.getValueAt(i, 1).toString();
//            String AccType = historyAdminTbl.getValueAt(i, 2).toString();
//            String Trans = historyAdminTbl.getValueAt(i, 3).toString();
//            String Date= historyAdminTbl.getValueAt(i, 4).toString();
//            String Time= historyAdminTbl.getValueAt(i, 5).toString();
//            String Amount = historyAdminTbl.getValueAt(i, 6).toString();
//         
//            
//            tf.append("\n"+Customer);
//            tf.append("\t"+Cardnumber);
//            tf.append("\t"+AccType);
//            tf.append("\t"+Trans);
//            tf.append("\t    "+Date);
//            tf.append("\t  "+Time);
//            tf.append("\t"+Amount);
//            
//            }
//            
//            Font f = new Font("Times New Roman",Font.PLAIN,12);
//            tf.setFont(f);
//        try {
//            Boolean flag =tf.print();
//        } catch (PrinterException ex) {
//            System.out.println("hey yha dikkat aa rhi h");
//            Logger.getLogger(MiniStatement.class.getName()).log(Level.SEVERE, null, ex);
//        }
}
