/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor1;

import java.awt.Color;
//import java.util.Date;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class AtmPin extends javax.swing.JFrame {
  

    /**
     * Creates new form BankLogin
     */
  public static String userName,cardNumber,pin="0";
  
    public AtmPin() {
        initComponents();
        jPanel1.setFocusable(true);
        userNameTF.setBackground(new Color(0,0,0,0));
        cardNumberTF.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameLbl1 = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();
        cardNumberTF = new javax.swing.JTextField();
        pinPF = new javax.swing.JPasswordField();
        enterBtn = new javax.swing.JToggleButton();
        cancelBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        nameLbl1.setBackground(new java.awt.Color(255, 255, 204));
        nameLbl1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        nameLbl1.setForeground(new java.awt.Color(255, 255, 204));
        nameLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLbl1.setText("Enter 4 digit pin");
        jPanel1.add(nameLbl1);
        nameLbl1.setBounds(240, 160, 160, 30);

        userNameTF.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        userNameTF.setForeground(new java.awt.Color(204, 204, 204));
        userNameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userNameTF.setText("username");
        userNameTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(0, 204, 204)));
        userNameTF.setOpaque(false);
        userNameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameTFFocusLost(evt);
            }
        });
        jPanel1.add(userNameTF);
        userNameTF.setBounds(170, 50, 310, 50);

        cardNumberTF.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        cardNumberTF.setForeground(new java.awt.Color(204, 204, 204));
        cardNumberTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cardNumberTF.setText("card number");
        cardNumberTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 204, 204)));
        cardNumberTF.setOpaque(false);
        cardNumberTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardNumberTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardNumberTFFocusLost(evt);
            }
        });
        jPanel1.add(cardNumberTF);
        cardNumberTF.setBounds(170, 110, 310, 50);

        pinPF.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pinPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(pinPF);
        pinPF.setBounds(220, 190, 160, 40);

        enterBtn.setBackground(new java.awt.Color(0, 51, 153));
        enterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minor1/enter-2.png"))); // NOI18N
        enterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterBtn.setOpaque(true);
        enterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBtnActionPerformed(evt);
            }
        });
        jPanel1.add(enterBtn);
        enterBtn.setBounds(390, 190, 40, 40);

        cancelBtn.setBackground(new java.awt.Color(0, 153, 153));
        cancelBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minor1/ic_cancel_24px_1.png"))); // NOI18N
        cancelBtn.setText(" CANCEL");
        cancelBtn.setBorder(null);
        cancelBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn);
        cancelBtn.setBounds(40, 250, 110, 40);

        clearBtn.setBackground(new java.awt.Color(0, 153, 153));
        clearBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minor1/trash-simple-2.png"))); // NOI18N
        clearBtn.setText("CLEAR");
        clearBtn.setBorder(null);
        clearBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn);
        clearBtn.setBounds(160, 250, 110, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minor1/atm.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 501, 314);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTFFocusGained
        // TODO add your handling code here:    [255,255,51]
        userNameTF.setBackground(new Color(0,0,0,64));
        if(userNameTF.getText().equals("username")){
            userNameTF.setText("");
            userNameTF.setForeground(Color.YELLOW);
        }
        
    }//GEN-LAST:event_userNameTFFocusGained

    private void cardNumberTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardNumberTFFocusGained
        // TODO add your handling code here:
        cardNumberTF.setBackground(new Color(0,0,0,64));
        if(cardNumberTF.getText().equals("card number")){
            cardNumberTF.setText("");
            cardNumberTF.setForeground(Color.yellow);
        }
        
    }//GEN-LAST:event_cardNumberTFFocusGained

    private void userNameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTFFocusLost
         if(userNameTF.getText().trim().equals("")){
             userNameTF.setBackground(new Color(0,0,0,0));
             userNameTF.setForeground(new Color(204,204,204));
            userNameTF.setText("username"); 
        }
//         else{
//        userName = userNameTF.getText().toLowerCase().trim();
//        System.out.println(userName);
//         }
         
    }//GEN-LAST:event_userNameTFFocusLost

    private void cardNumberTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardNumberTFFocusLost
        // TODO add your handling code here
        if(cardNumberTF.getText().trim().equals("")){
            cardNumberTF.setBackground(new Color(0,0,0,0));
            cardNumberTF.setForeground(new Color(204,204,204));
            cardNumberTF.setText("card number");
        }
//        else{
//            cardNumber = userNameTF.getText().toLowerCase().trim();
//            System.out.println(cardNumber);
//        }
    }//GEN-LAST:event_cardNumberTFFocusLost

    private void enterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBtnActionPerformed
        // TODO add your handling code here:
        UserLogin ul = new UserLogin();
         userName = userNameTF.getText().trim();
        cardNumber = cardNumberTF.getText().trim();
        pin = pinPF.getText().trim();

        
        //checking if the card is blocked???
        Boolean status = ul.checkStatus();
        if(status){
            JOptionPane.showMessageDialog(this,"THIS CARD HAS BEEN BLOCKED\nCONTACT YOUR BANK");
              userNameTF.setText("");
                cardNumberTF.setText("");
                pinPF.setText("");
                jPanel1.setFocusable(true);
        }
        else{
//      boolean flag =  new UserLogin(userName,cardNumber,pin).check();
         boolean flag =  ul.check();

      if(flag){
          long millis=System.currentTimeMillis();
          Date todayDate=new Date(millis);
          UserTransaction ut = new UserTransaction();
          Date lastDate = ut.checkLastDate();
          System.out.println("Today's Date: "+todayDate+"\nLast Login Date: "+lastDate);
           String StodayDate = String.valueOf(todayDate);
           String SlastDate = String.valueOf(lastDate);
          if(!StodayDate.equals(SlastDate)){
              System.out.println("Everything reset!!");
              ut.reset();
          }

          this.setVisible(false);
          new SavCurCheck().setVisible(true);
//      new UserHome(userName,cardNumber).setVisible(true);
      }
      else{
          JOptionPane.showMessageDialog(this, "Wrong Login Details\nTry again or Contact your bank");
          userNameTF.setText("");
          cardNumberTF.setText("");
          pinPF.setText("");
          
          jPanel1.setFocusable(true);
          

            
         } 
       }
    }//GEN-LAST:event_enterBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new nav().setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
           userNameTF.setText("");
          cardNumberTF.setText("");
          pinPF.setText("");
          
          jPanel1.setFocusable(true);
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtmPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtmPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtmPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtmPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtmPin().setVisible(true);
            }
        });
//        Minor1 m = new Minor1();
//        new Minor1().jtfTransparent(userNameTF);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField cardNumberTF;
    private javax.swing.JButton clearBtn;
    private javax.swing.JToggleButton enterBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JPasswordField pinPF;
    private javax.swing.JTextField userNameTF;
    // End of variables declaration//GEN-END:variables
}
