/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor1;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;


/**
 *
 * @author Lenovo
 */
public class Fastcash extends javax.swing.JFrame {
//int amount;
    /**
     * Creates new form Fastcash
     */
    public Fastcash() {
        initComponents();
        jPanel1.setFocusable(true);
        int withdrawLimit= new UserTransaction().checkWithdrawLimit();
        if(SavCurCheck.saving)
        JOptionPane.showMessageDialog(this, "YOUR DAILY WITHDRAW LIMIT IS 10,000/-\nYOU CAN WITHDRAW "+ withdrawLimit+"/- MORE!!!\nTHIS AMOUNT RESETS IN 24 HOURS");

    }
    
//          only for design purpose
        public void setBtnColor(JToggleButton jb)
    {
          jb.setBackground(new Color(0,204,204));
          jb.setForeground(Color.black);
    }
    
    public void removeBtnColor(JToggleButton jb)
    {
        jb.setBackground(new Color(0,44,62));
        jb.setForeground(Color.white);
    }
    
    
    // amount function send request to withdraw function
    void amount(int amount){
    UserTransaction ut = new UserTransaction();
        int balance =ut.checkBalance();
       
                    int withdrawlimit = ut.checkWithdrawLimit();
                     
                    if(amount>=balance){
                                    JOptionPane.showMessageDialog(this, "YOU CANNOT MAKE THE TRANSACTION\n!!! ACCOUNT BALANCE IS:  "+balance);

                    }
                   else if(amount>withdrawlimit){
                          JOptionPane.showMessageDialog(this, "YOU CAN WITHDRAW "+ withdrawlimit+"/- MORE!!!");                     
                     }

                    
                    else{
                                    JOptionPane.showMessageDialog(this, "YOU ARE ABOUT TO WITHDRAW  " + amount + " and your account balance is "+balance);
                                    JOptionPane.showMessageDialog(this, "ADMIN/OWNER MUST LOGIN TO CONFIRM PAYMENT!!!");
                                   this.setVisible(false);
                                    new Login("withdraw",amount).setVisible(true);
                           }
                     System.out.println(amount);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Loginlb = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn100 = new javax.swing.JToggleButton();
        btn1000 = new javax.swing.JToggleButton();
        btn5000 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        btn500 = new javax.swing.JToggleButton();
        btn2000 = new javax.swing.JToggleButton();
        btn10000 = new javax.swing.JToggleButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(466, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(466, 400));

        Loginlb.setBackground(new java.awt.Color(0, 204, 204));
        Loginlb.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Loginlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Loginlb.setText("FASTCASH");
        Loginlb.setOpaque(true);

        jPanel2.setOpaque(false);

        btn100.setBackground(new java.awt.Color(0, 44, 62));
        buttonGroup1.add(btn100);
        btn100.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btn100.setForeground(new java.awt.Color(255, 255, 255));
        btn100.setText("₹100");
        btn100.setBorder(null);
        btn100.setBorderPainted(false);
        btn100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn100.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn100.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn100MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn100MouseExited(evt);
            }
        });
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });

        btn1000.setBackground(new java.awt.Color(0, 44, 62));
        buttonGroup1.add(btn1000);
        btn1000.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btn1000.setForeground(new java.awt.Color(255, 255, 255));
        btn1000.setText("₹1,000");
        btn1000.setBorder(null);
        btn1000.setBorderPainted(false);
        btn1000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1000.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1000.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn1000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1000MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1000MouseExited(evt);
            }
        });
        btn1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000ActionPerformed(evt);
            }
        });

        btn5000.setBackground(new java.awt.Color(0, 44, 62));
        buttonGroup1.add(btn5000);
        btn5000.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btn5000.setForeground(new java.awt.Color(255, 255, 255));
        btn5000.setText("₹5,000");
        btn5000.setBorder(null);
        btn5000.setBorderPainted(false);
        btn5000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5000.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn5000.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn5000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn5000MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn5000MouseExited(evt);
            }
        });
        btn5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5000ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn5000, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(btn100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn100, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1000, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn5000, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setOpaque(false);

        btn500.setBackground(new java.awt.Color(0, 44, 62));
        buttonGroup1.add(btn500);
        btn500.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btn500.setForeground(new java.awt.Color(255, 255, 255));
        btn500.setText("₹500");
        btn500.setBorder(null);
        btn500.setBorderPainted(false);
        btn500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn500.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn500.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn500MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn500MouseExited(evt);
            }
        });
        btn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500ActionPerformed(evt);
            }
        });

        btn2000.setBackground(new java.awt.Color(0, 44, 62));
        buttonGroup1.add(btn2000);
        btn2000.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btn2000.setForeground(new java.awt.Color(255, 255, 255));
        btn2000.setText("₹2,000");
        btn2000.setBorder(null);
        btn2000.setBorderPainted(false);
        btn2000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2000.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2000.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn2000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2000MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2000MouseExited(evt);
            }
        });
        btn2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2000ActionPerformed(evt);
            }
        });

        btn10000.setBackground(new java.awt.Color(0, 44, 62));
        buttonGroup1.add(btn10000);
        btn10000.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btn10000.setForeground(new java.awt.Color(255, 255, 255));
        btn10000.setText("₹10,000");
        btn10000.setBorder(null);
        btn10000.setBorderPainted(false);
        btn10000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn10000.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn10000.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn10000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn10000MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn10000MouseExited(evt);
            }
        });
        btn10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10000ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn2000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn10000, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn500, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn2000, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn10000, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        exitBtn.setBackground(new java.awt.Color(204, 0, 0));
        exitBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Go Back");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Loginlb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn)
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Loginlb, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
amount(100);
    }//GEN-LAST:event_btn100ActionPerformed

    private void btn1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000ActionPerformed
        // TODO add your handling code here:
        amount(1000);

    }//GEN-LAST:event_btn1000ActionPerformed

    private void btn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500ActionPerformed
        // TODO add your handling code here:
       amount(500);

    }//GEN-LAST:event_btn500ActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UserHome().setVisible(true);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void btn2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2000ActionPerformed
        // TODO add your handling code here:
        amount(2000);

    }//GEN-LAST:event_btn2000ActionPerformed

    private void btn5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5000ActionPerformed
        // TODO add your handling code here:
        amount(5000);

    }//GEN-LAST:event_btn5000ActionPerformed

    private void btn10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10000ActionPerformed
        // TODO add your handling code here:
        amount(10000);

    }//GEN-LAST:event_btn10000ActionPerformed

    private void btn100MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn100MouseEntered
        // TODO add your handling code here:
        setBtnColor(btn100);
    }//GEN-LAST:event_btn100MouseEntered

    private void btn500MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn500MouseEntered
        // TODO add your handling code here:
        setBtnColor(btn500);
    }//GEN-LAST:event_btn500MouseEntered

    private void btn1000MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1000MouseEntered
        // TODO add your handling code here:
        setBtnColor(btn1000);
    }//GEN-LAST:event_btn1000MouseEntered

    private void btn2000MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2000MouseEntered
        // TODO add your handling code here:
        setBtnColor(btn2000);
    }//GEN-LAST:event_btn2000MouseEntered

    private void btn5000MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5000MouseEntered
        // TODO add your handling code here:
        setBtnColor(btn5000);
    }//GEN-LAST:event_btn5000MouseEntered

    private void btn10000MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10000MouseEntered
        // TODO add your handling code here:
        setBtnColor(btn10000);
    }//GEN-LAST:event_btn10000MouseEntered

    private void btn100MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn100MouseExited
        // TODO add your handling code here:
        removeBtnColor(btn100);
    }//GEN-LAST:event_btn100MouseExited

    private void btn500MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn500MouseExited
        // TODO add your handling code here:
        removeBtnColor(btn500);
    }//GEN-LAST:event_btn500MouseExited

    private void btn1000MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1000MouseExited
        // TODO add your handling code here:
        removeBtnColor(btn1000);
    }//GEN-LAST:event_btn1000MouseExited

    private void btn2000MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2000MouseExited
        // TODO add your handling code here:
        removeBtnColor(btn2000);
    }//GEN-LAST:event_btn2000MouseExited

    private void btn5000MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5000MouseExited
        // TODO add your handling code here:
        removeBtnColor(btn5000);
    }//GEN-LAST:event_btn5000MouseExited

    private void btn10000MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10000MouseExited
        // TODO add your handling code here:
        removeBtnColor(btn10000);
    }//GEN-LAST:event_btn10000MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fastcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fastcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fastcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fastcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fastcash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Loginlb;
    private javax.swing.JToggleButton btn100;
    private javax.swing.JToggleButton btn1000;
    private javax.swing.JToggleButton btn10000;
    private javax.swing.JToggleButton btn2000;
    private javax.swing.JToggleButton btn500;
    private javax.swing.JToggleButton btn5000;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
